[project]
name = "smart-retrieval-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "chromadb>=1.5.5",
    "fastapi>=0.135.1",
    "langchain>=0.3.1",
    "langchain-community>=0.3.1",
    "langchain-core>=0.3.1",
    "langchain-experimental>=0.3.1",
    "langfuse>=4.0.0",
    "numpy>=2.1.0",
    "openpyxl>=3.1.5",
    "pdfplumber>=0.11.9",
    "pydantic>=2.12.5",
    "python-docx>=1.2.0",
    "rank-bm25>=0.2.2",
    "requests>=2.32.5",
    "unstructured>=0.21.5",
    "uvicorn>=0.42.0",
]
